####################
# СПАЛЬНАЯ КОМНАТА #
####################

# Компьютер
# https://www.home-assistant.io/integrations/wake_on_lan/
- platform: wake_on_lan
  name: desktop_pc
  mac: "48:5B:39:AA:52:2A"
  host: "192.168.1.5"
  turn_off:
    service: hassio.addon_stdin
    data:
      addon: core_rpc_shutdown 
      input: desktop_pc
