###########
# КОРИДОР #
###########

# Режим спаривания ZigBee шлюза
- platform: mqtt
  name: gateway_join
  icon: mdi:access-point-network
  availability_topic: "/zigbee/bridge/state"
  state_topic: "/zigbee/bridge/config"
  value_template: "{{ value_json.permit_join }}"
  state_on: true
  state_off: false
  command_topic: "/zigbee/bridge/config/permit_join"
  payload_on: "true"
  payload_off: "false"

# Охранная система
- platform: mqtt
  name: security_system
  command_topic: "megad/cmd"
  payload_on: '{"port":29,"value":"ON"}'
  payload_off: '{"port":29,"value":"OFF"}'
  state_topic: "megad/29"
  value_template: >-
    {% if value_json.value == "ON" %}
      {"port":29,"value":"ON"}
    {% else %}
      {"port":29,"value":"OFF"}
    {% endif %}
