# Вытяжка (гигростат)
- platform: template
  switches:
    kitchen_fan_hygrostat:
      value_template: "{{ is_state('climate.kitchen', 'fan_only') }}"
      turn_on:
        service: climate.set_hvac_mode
        entity_id: climate.kitchen
        data:
          hvac_mode: "fan_only"
      turn_off:
        service: script.kitchen_turnoff_fan_only_mode
