# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include_dir_merge_named customize/
  # Authorization
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/16
        - fc00::/7
      allow_bypass_login: true
    - type: homeassistant
  # For filesize sensor
  whitelist_external_dirs:
    - /config

# Lovelace UI
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/vacuum-card/vacuum-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /browser_mod.js
      type: module
    - url: /hacsfiles/ha-yandex-icons/yandex-icons.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module

# https://github.com/thomasloven/hass-browser_mod
browser_mod:
  disable:
    - all

# Using SSL/TLS
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

# History
recorder:
  purge_keep_days: 7
  include: # Включить в историю
    domains:
      - sensor
      - climate
      - input_boolean
    entities:
      - binary_sensor.doorbell_button_binary_input_1
      - binary_sensor.hallway_motion_occupancy
  exclude: # Исключить из истории
    entities:
      # Системные
      - sensor.ipv4_address_eth0
      - sensor.last_boot
      - sensor.home_assistant_v2_db
      - sensor.snapshot_backup
      - sensor.gateway_uptime
      - sensor.hacs
      # Состояние батареек датчиков
      - sensor.bathroom_sensor_battery
      - sensor.bathroom_leak_1_battery
      - sensor.bathroom_leak_2_battery
      - sensor.bathroom_button_battery
      - sensor.bathroom_motion_battery
      - sensor.bedroom_sensor_battery
      - sensor.doorbell_button_battery
      - sensor.coolant_sensor_battery
      - sensor.hallway_door_battery
      - sensor.hallway_motion_battery
      - sensor.hallway_sensor_battery
      - sensor.kitchen_sensor_battery
      - sensor.kitchen_leak_battery
      - sensor.loggia_sensor_battery
      - sensor.lounge_sensor_battery
      - sensor.xiaomi_redmi_note_8t_battery
      - sensor.xiaomi_robot_battery
      # Разное
      - sensor.home_sensor_humidity
      - sensor.home_sensor_temperature
      - sensor.hallway_motion_illuminance

# Elfin-EE11
modbus:
  name: elfin
  type: tcp
  host: 192.168.1.4
  port: 502

# Xiaomi Mi Robot Vacuum
# https://www.home-assistant.io/integrations/vacuum.xiaomi_miio/
vacuum:
  - platform: xiaomi_miio
    name: xiaomi_robot
    host: 192.168.1.15
    token: !secret xiaomi_vacuum_token

# OpenWRT Device Tracker
device_tracker:
  - platform: luci
    host: 192.168.1.1
    username: !secret openwrt_login
    password: !secret openwrt_password

# Yandex.Alice
yandex_station:
  username: !secret yandex_login
  password: !secret yandex_password

# Devices
sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
switch: !include_dir_merge_list switches/
light: !include_dir_merge_list lights/
fan: !include_dir_merge_list fans/
climate: !include_dir_merge_list climates/
media_player: !include_dir_merge_list media_players/
utility_meter: !include_dir_merge_named utility_meters/

# Other
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
input_text: !include_dir_merge_named input_texts/
alarm_control_panel: !include alarm_control_panel.yaml
shell_command: !include shell_commands.yaml

# Voice assistant
yandex_smart_home: !include yandex_smart_home.yaml
