title: Моя квартира
views:
  # Общая информация
  - title: "Общая информация"
    path: default
    icon: mdi:information
    panel: true
    cards:
      - type: picture-elements
        image: "/local/home_map.png"
        elements:
          # Охрана
          - type: state-icon
            entity: alarm_control_panel.home
            style:
              top: 66%
              left: 30.9%
          # Коридор
          - type: state-icon # Освещение
            tap_action:
              action: toggle
            entity: light.hallway
            style:
              top: 60.5%
              left: 30%
          - type: state-icon # Подсветка шлюза
            entity: light.gateway
            style:
              top: 57%
              left: 38%
          - type: state-label # Температура
            entity: sensor.hallway_sensor_temperature
            prefix: "Температура: "
            style:
              top: 62%
              left: 38%
          - type: state-label # Влажность
            entity: sensor.hallway_sensor_humidity
            prefix: "Влажность: "
            style:
              top: 64%
              left: 38%
          - type: state-icon # Датчик движения
            entity: binary_sensor.hallway_motion_occupancy
            style:
              top: 60.5%
              left: 22%
          - type: state-icon # Датчик входной двери
            entity: binary_sensor.hallway_door_contact
            style:
              top: 66%
              left: 28.9%
          # Спальня
          - type: state-icon # Освещение
            tap_action:
              action: toggle
            entity: light.bedroom
            style:
              top: 35%
              left: 29.5%
          - type: state-icon # Настольный компьютер
            entity: media_player.desktop_pc
            style:
              top: 24%
              left: 36%
          - type: state-label # Температура
            entity: sensor.bedroom_temperature
            prefix: "Температура: "
            style:
              top: 40%
              left: 29.5%
          - type: state-label # Влажность
            entity: sensor.bedroom_humidity
            prefix: "Влажность: "
            style:
              top: 42%
              left: 29.5%
          # Зал
          - type: state-icon # Основное освещение
            tap_action:
              action: toggle
            entity: light.lounge_first
            style:
              top: 36%
              left: 55%
          - type: state-icon # Дополнительное освещение
            tap_action:
              action: toggle
            entity: light.lounge_second
            style:
              top: 36%
              left: 57%
          - type: state-icon # Телевизор
            entity: media_player.lounge_tv
            icon: mdi:television
            style:
              top: 36%
              left: 69%
          - type: state-icon # Робот пылесос
            entity: vacuum.xiaomi_robot
            style:
              top: 23.5%
              left: 69%
          - type: state-label # Температура
            entity: sensor.lounge_temperature
            prefix: "Температура: "
            style:
              top: 41%
              left: 56%
          - type: state-label # Влажность
            entity: sensor.lounge_humidity
            prefix: "Влажность: "
            style:
              top: 43%
              left: 56%
          # Кухня
          - type: state-icon # Освещение
            tap_action:
              action: toggle
            entity: light.kitchen
            style:
              top: 71%
              left: 62%
          - type: state-icon # Вытяжка
            entity: climate.kitchen
            style:
              top: 82%
              left: 65%
          - type: state-icon # Газовый котел
            entity: climate.gas_boiler
            style:
              top: 82%
              left: 53%
          - type: state-icon # Теплый пол
            entity: climate.warm_floor
            style:
              top: 82%
              left: 55%
          - type: state-icon # Датчик протечки
            entity: binary_sensor.kitchen_leak_water_leak
            style:
              top: 82%
              left: 57%
          - type: state-icon # Телевизор
            entity: media_player.kitchen_tv
            style:
              top: 63%
              left: 53%
          - type: state-label # Температура
            entity: sensor.kitchen_sensor_temperature
            prefix: "Температура: "
            style:
              top: 62%
              left: 62%
          - type: state-label # Влажность
            entity: sensor.kitchen_sensor_humidity
            prefix: "Влажность: "
            style:
              top: 64%
              left: 62%
          # Лоджия
          - type: state-icon # Освещение
            tap_action:
              action: toggle
            entity: light.loggia
            style:
              top: 69%
              left: 75%
          - type: state-label # Температура
            entity: sensor.loggia_sensor_temperature
            prefix: "Температура: "
            style:
              top: 73%
              left: 75%
          - type: state-label # Влажность
            entity: sensor.loggia_sensor_humidity
            prefix: "Влажность: "
            style:
              top: 75%
              left: 75%
          - type: state-label # Давление
            entity: sensor.loggia_sensor_pressure
            prefix: "Давление: "
            style:
              top: 77%
              left: 75%
          # Ванная
          - type: state-icon # Освещение
            tap_action:
              action: toggle
            entity: light.bathroom
            style:
              top: 82%
              left: 42.6%
          - type: state-icon # Вентиляция
            entity: climate.bathroom
            style:
              top: 82%
              left: 49%
          - type: state-label # Температура
            entity: sensor.bathroom_sensor_temperature
            prefix: "Температура: "
            style:
              top: 76%
              left: 42.5%
          - type: state-label # Влажность
            entity: sensor.bathroom_sensor_humidity
            prefix: "Влажность: "
            style:
              top: 78%
              left: 42.5%
          - type: state-icon # Датчик протечки №1
            entity: binary_sensor.bathroom_leak_1_water_leak
            style:
              top: 82%
              left: 38%
          - type: state-icon # Датчик протечки №2
            entity: binary_sensor.bathroom_leak_2_water_leak
            style:
              top: 82%
              left: 47%
          - type: state-icon # Водоснабжение
            entity: switch.water_valve_switch
            style:
              top: 82%
              left: 36%

  # Обзор комнат
  - title: "Обзор комнат"
    path: rooms
    icon: mdi:home
    cards:
      - type: alarm-panel
        #name: "Охранная система"
        entity: alarm_control_panel.home
        states:
          - arm_away
          - arm_night
      - type: entities
        title: "Коридор"
        show_header_toggle: false
        entities:
          - light.hallway
          - light.gateway
          - sensor.hallway_sensor_temperature
          - sensor.hallway_sensor_humidity
          - entity: binary_sensor.hallway_motion_occupancy
            secondary_info: last-changed
            state_color: true
          - entity: binary_sensor.hallway_door_contact
            secondary_info: last-changed
            state_color: true
      - type: entities
        title: "Спальня"
        show_header_toggle: false
        entities:
          - light.bedroom
          - entity: media_player.desktop_pc
            state_color: true
          - sensor.bedroom_temperature
          - sensor.bedroom_humidity
      - type: entities
        title: "Зал"
        show_header_toggle: false
        entities:
          - light.lounge_first
          - light.lounge_second
          - entity: media_player.lounge_tv
            icon: mdi:television
            state_color: true
          - entity: vacuum.xiaomi_robot
            state_color: true
          - sensor.lounge_temperature
          - sensor.lounge_humidity
      - type: entities
        title: "Кухня"
        show_header_toggle: false
        entities:
          - light.kitchen
          - entity: media_player.kitchen_tv
            state_color: true
          - entity: climate.kitchen
            state_color: true
          - entity: climate.gas_boiler
            state_color: true
          - entity: climate.warm_floor
            state_color: true
          - sensor.kitchen_sensor_temperature
          - entity: binary_sensor.kitchen_leak_water_leak
            secondary_info: last-changed
            state_color: true
      - type: entities
        title: "Лоджия"
        show_header_toggle: false
        entities:
          - light.loggia
          - sensor.loggia_sensor_temperature
          - sensor.loggia_sensor_humidity
          - sensor.loggia_sensor_pressure
      - type: entities
        title: "Ванная"
        show_header_toggle: false
        entities:
          - light.bathroom
          - entity: climate.bathroom
            state_color: true
          - sensor.bathroom_sensor_temperature
          - entity: binary_sensor.bathroom_leak_1_water_leak
            secondary_info: last-changed
            state_color: true
          - entity: binary_sensor.bathroom_leak_2_water_leak
            secondary_info: last-changed
            state_color: true
          - entity: switch.water_valve_switch
            state_color: true

  # Энергоснабжение
  - title: "Энергоснабжение"
    path: electric
    icon: mdi:flash
    cards:
      - type: gauge
        entity: sensor.energy_line_voltage
        min: 180
        max: 280
        severity:
          green: 215
          yellow: 0
          red: 245
      - type: history-graph
        title: "Сетевое напряжение"
        hours_to_show: 24
        refresh_interval: 30
        entities:
          - entity: sensor.energy_line_voltage
      - type: gauge
        entity: sensor.energy_line_frequency
        min: 49
        max: 51
        severity:
          green: 49.95
          yellow: 0
          red: 50.06
      - type: history-graph
        title: "Коэффициент мощности"
        hours_to_show: 24
        refresh_interval: 30
        entities:
          - entity: sensor.energy_line_coefficient
      - type: gauge
        entity: sensor.energy_line_current
        min: 0
        max: 40
        severity:
          green: 0
          yellow: 12
          red: 24
      - type: history-graph
        title: "Нагрузка на сеть"
        hours_to_show: 24
        refresh_interval: 30
        entities:
          - entity: sensor.energy_line_current
      - type: entities
        title: "Потребление за час"
        entities:
          - entity: sensor.energy_line_hourly_kwh
          - entity: sensor.energy_line_hourly_rub
      - type: entities
        title: "Потребление за день"
        entities:
          - entity: sensor.energy_line_daily_kwh
          - entity: sensor.energy_line_daily_rub
      - type: entities
        title: "Потребление за месяц"
        entities:
          - entity: sensor.energy_line_monthly_kwh
          - entity: sensor.energy_line_monthly_rub

  # Погодные условия
  - title: "Погодные условия"
    path: weather
    icon: mdi:cloud
    panel: true
    cards:
        - type: horizontal-stack
          cards:
            - type: custom:weather-card-chart
              title: "Прогноз погоды"
              weather: weather.dark_sky
            - type: history-graph
              title: "Атмосферное давление"
              hours_to_show: 24
              refresh_interval: 30
              entities:
                - entity: sensor.loggia_sensor_pressure
            - type: history-graph
              title: "Уровень радиации"
              hours_to_show: 24
              refresh_interval: 30
              entities:
                - entity: sensor.radiation_level_filtered

  # Мультимедиа
  - title: "Мультимедиа"
    path: multimedia
    icon: mdi:youtube
    cards:
      - type: media-control
        entity: media_player.desktop_pc
      - type: media-control
        entity: media_player.lounge_tv
      - type: media-control
        entity: media_player.kitchen_tv

  # Уборка квартиры
  - title: "Уборка квартиры"
    path: cleaning
    icon: mdi:robot-vacuum
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: vacuum.xiaomi_robot
                state_color: true
          # https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card
          - type: custom:xiaomi-vacuum-map-card
            entity: vacuum.xiaomi_robot
            map_image: "/local/vacuum_map.png"
            default_mode: predefined_zones
            language: ru
            calibration_points:
              - vacuum:
                  x: 17300
                  y: 25850
                map:
                  x: 460
                  y: 125
              - vacuum:
                  x: 17300
                  y: 20500
                map:
                  x: 460
                  y: 675
              - vacuum:
                  x: 27750
                  y: 20500
                map:
                  x: 1485
                  y: 675
            zones:
              - [[17325, 22220, 18480, 23190], [18480, 22080, 22450, 23190]]
              - [[17325, 23370, 20630, 25855]]
              - [[20810, 23370, 25855, 25855], [21550, 23030, 25855, 23373]]
              - [[22620, 20760, 25855, 22870], [25855, 20960, 26560, 22610]]
              - [[26560, 20810, 27480, 25855]]
              - [[19720, 20760, 22450, 21970]]

  # Элементы питания
  - title: "Элементы питания"
    path: batteries
    icon: mdi:battery-charging
    cards:
      - type: custom:auto-entities
        card:
          type: entities
          title: "Состояние батареек"
          show_header_toggle: false
        filter:
          include:
            - entity_id: "sensor.*_battery"
        sort:
          method: state
          numeric: true

  # Сервис
  - title: "Сервис"
    path: service
    icon: mdi:settings
    panel: true
    cards:
        - type: horizontal-stack
          cards:
            - type: entities
              title: "Система"
              show_header_toggle: false
              entities:
                - sensor.gateway_uptime
                - sensor.last_boot
                - sensor.home_assistant_v2_db
                - sensor.memory_use_percent
                - sensor.swap_use_percent
                - sensor.disk_use_percent
                - sensor.processor_use
                - sensor.cpu_temperature
            - type: entities
              title: "Управление"
              show_header_toggle: false
              entities:
                - entity: switch.gateway_join
                  state_color: true
                - script.reboot_gateway
                - script.create_system_backup
                - script.restart_homeassistant
                - script.reboot_server
                - script.shutdown_server
