######################
# ОСВЕЩЕНИЕ В ВАННОЙ #
######################

- platform: mqtt
  name: bathroom
  command_topic: "megad/cmd"
  payload_on: '{"port":6,"value":"ON"}'
  payload_off: '{"port":6,"value":"OFF"}'
  state_topic: "megad/6"
  state_value_template: >-
    {% if value_json.value == "ON" %}
      {"port":6,"value":"ON"}
    {% else %}
      {"port":6,"value":"OFF"}
    {% endif %}
