############
# СПАЛЬНАЯ #
############

# Датчик температуры/влажности
# FIXME: временная заглушка!
- platform: template
  sensors:
    bedroom_temperature:
      friendly_name: "Температура"
      icon_template: mdi:thermometer
      unit_of_measurement: "°C"
      value_template: "{{ states('sensor.hallway_sensor_temperature') }}"
    bedroom_humidity:
      friendly_name: "Влажность"
      icon_template: mdi:water-percent
      unit_of_measurement: "%"
      value_template: "{{ states('sensor.hallway_sensor_humidity') }}"
    bedroom_sensor_battery:
      friendly_name: "Датчик температуры/влажности в спальне"
      icon_template: mdi:battery
      unit_of_measurement: "%"
      value_template: "100"
