# Датчик температуры/влажности
- platform: mqtt # Температура
  name: hallway_temperature
  icon: mdi:thermometer
  unit_of_measurement: "°C"
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/hallway_sensor"
  value_template: "{{ value_json.temperature | round(2) }}"
- platform: mqtt # Влажность
  name: hallway_humidity
  icon: mdi:water-percent
  unit_of_measurement: "%"
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/hallway_sensor"
  value_template: "{{ value_json.humidity | round(2) }}"
- platform: mqtt # Уровень заряда
  name: hallway_sensor_battery
  icon: mdi:battery-high
  unit_of_measurement: "%"
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/hallway_sensor"
  value_template: "{{ value_json.battery }}"

# Датчик движения
- platform: mqtt # Освещение
  name: hallway_illuminance
  icon: mdi:brightness-6
  unit_of_measurement: "" # лк / lx
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/hallway_motion"
  value_template: "{{ value_json.illuminance }}"
- platform: mqtt # Уровень заряда
  name: hallway_motion_battery
  icon: mdi:battery-high
  unit_of_measurement: "%"
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/hallway_motion"
  value_template: "{{ value_json.battery }}"

# Датчик открытия входной двери
- platform: mqtt # Уровень заряда
  name: hallway_door_battery
  icon: mdi:battery-high
  unit_of_measurement: "%"
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/hallway_door"
  value_template: "{{ value_json.battery }}"
