# Датчик температуры/влажности
- platform: mqtt # Температура
  name: kitchen_temperature
  icon: mdi:thermometer
  unit_of_measurement: "°C"
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/kitchen_sensor"
  value_template: "{{ value_json.temperature | round(2) }}"
- platform: mqtt # Влажность
  name: kitchen_humidity
  icon: mdi:water-percent
  unit_of_measurement: "%"
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/kitchen_sensor"
  value_template: "{{ value_json.humidity | round(2) }}"
  force_update: true
- platform: mqtt # Уровень заряда
  name: kitchen_sensor_battery
  icon: mdi:battery-high
  unit_of_measurement: "%"
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/kitchen_sensor"
  value_template: "{{ value_json.battery }}"

# Датчик температуры насоса теплого пола
- platform: mqtt # Температура
  name: floor_pump_temperature
  icon: mdi:thermometer
  unit_of_measurement: "°C"
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/floor_pump_sensor"
  value_template: "{{ value_json.temperature | round(2) }}"
  force_update: true
- platform: mqtt # Уровень заряда
  name: floor_pump_sensor_battery
  icon: mdi:battery-high
  unit_of_measurement: "%"
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/floor_pump_sensor"
  value_template: "{{ value_json.battery }}"

# Датчик протечки
- platform: mqtt
  name: kitchen_leak_battery
  icon: mdi:battery-high
  unit_of_measurement: "%"
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/kitchen_leak"
  value_template: "{{ value_json.battery }}"
