# Датчик температуры теплоносителя
# FIXME: временная заглушка!
- platform: template
  sensors:
    coolant_temperature:
      friendly_name: "Температура теплоносителя"
      icon_template: mdi:thermometer
      unit_of_measurement: "°C"
      value_template: "{{ states('sensor.hallway_sensor_temperature') }}"
    coolant_sensor_battery:
      friendly_name: "Датчик температуры теплоносителя"
      icon_template: mdi:battery
      unit_of_measurement: "%"
      value_template: "100"
      # BATTERY = 100 * (CURRENT_VALUE - MIN_VALUE) / (MAX_VALUE - MIN_VALUE)
