# ESP Radiation Meter
# https://github.com/avdeevsv91/esp_radiation_meter
- platform: mqtt
  name: radiation_level
  state_topic: "/radiation/valuedes0"
- platform: mqtt
  name: radiation_accuracy
  state_topic: "/radiation/valuedes1"
#- platform: mqtt
#  name: radiation_voltage
#  state_topic: "/radiation/valuedes2"

# Отфильтрованное значение
- platform: filter
  name: radiation_level_filtered
  entity_id: sensor.radiation_level
  filters:
    - filter: lowpass
      time_constant: 10

# Датчик температуры/влажности/давления
- platform: mqtt # Температура
  name: loggia_temperature
  icon: mdi:thermometer
  unit_of_measurement: "°C"
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/loggia_sensor"
  value_template: "{{ value_json.temperature | round(2) }}"
- platform: mqtt # Влажность
  name: loggia_humidity
  icon: mdi:water-percent
  unit_of_measurement: "%"
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/loggia_sensor"
  value_template: "{{ value_json.humidity | round(2) }}"
- platform: mqtt # Давление
  name: loggia_pressure
  icon: mdi:gauge
  unit_of_measurement: "мм рт.ст."
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/loggia_sensor"
  value_template: "{{ (value_json.pressure | float * 7.501) | round | int }}"
- platform: mqtt # Уровень заряда
  name: loggia_sensor_battery
  icon: mdi:battery-high
  unit_of_measurement: "%"
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/loggia_sensor"
  value_template: "{{ value_json.battery }}"
