# Датчик температуры/влажности
# FIXME: временная заглушка!
- platform: template
  sensors:
    lounge_temperature:
      friendly_name: "Температура"
      icon_template: mdi:thermometer
      unit_of_measurement: "°C"
      value_template: "{{ states('sensor.hallway_sensor_temperature') }}"
    lounge_humidity:
      friendly_name: "Влажность"
      icon_template: mdi:water-percent
      unit_of_measurement: "%"
      value_template: "{{ states('sensor.hallway_sensor_humidity') }}"
    lounge_sensor_battery:
      friendly_name: "Датчик температуры/влажности в зале"
      icon_template: mdi:battery
      unit_of_measurement: "%"
      value_template: "100"

# Робот-пылесос
- platform: template
  sensors:
    xiaomi_robot_battery:
      friendly_name: "Робот-пылесос"
      icon_template: mdi:battery
      unit_of_measurement: "%"
      value_template: "{{ state_attr('vacuum.xiaomi_robot', 'battery_level') }}"
