# Время работы шлюза
- platform: mqtt
  name: gateway_uptime
  icon: mdi:timeline-clock
  unit_of_measurement: ""
  availability_topic: "/zigbee/bridge/state"
  state_topic: "/zigbee/bridge/config"
  value_template: "{{ value_json.UptimeStr }}"
