# Датчик протечки №1
- platform: mqtt
  name: bathroom_leak_1
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/bathroom_leak_1"
  value_template: >-
    {% if value_json.water_leak == true %}
      {{'ON'}}
    {% else %}
      {{'OFF'}}
    {% endif %}

# Датчик протечки №2
- platform: mqtt
  name: bathroom_leak_2
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/bathroom_leak_2"
  value_template: >-
    {% if value_json.water_leak == true %}
      {{'ON'}}
    {% else %}
      {{'OFF'}}
    {% endif %}

# Кнопка включения вентиляции
# single, double, triple, quadruple
- platform: mqtt
  name: bathroom_button_single # Однократное нажатие
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/bathroom_button"
  value_template: >-
    {% if value_json.click == 'single' %}
      {{'ON'}}
    {% else %}
      {{'OFF'}}
    {% endif %}
