# Датчик движения
- platform: mqtt
  name: hallway_motion
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/hallway_motion"
  value_template: >-
    {% if value_json.occupancy == true %}
      {{'ON'}}
    {% else %}
      {{'OFF'}}
    {% endif %}
  off_delay: 7
