# Датчик движения
- platform: mqtt
  name: hallway_motion
  device_class: motion
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/hallway_motion"
  value_template: "{{ value_json.occupancy }}"
  payload_on: true
  payload_off: false
  off_delay: 7

# Датчик входной двери
- platform: mqtt
  name: hallway_door
  device_class: door
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/hallway_door"
  value_template: "{{ value_json.contact }}"
  payload_on: false
  payload_off: true
