# Датчик протечки
- platform: mqtt
  name: kitchen_leak
  device_class: moisture
  availability_topic: "/zigbee-ble/bridge/state"
  state_topic: "/zigbee-ble/kitchen_leak"
  value_template: "{{ value_json.water_leak }}"
  payload_on: true
  payload_off: false
