#####################################
# КЛИМАТИЧЕСКИЕ УСТРОЙСТВА НА КУХНЕ #
#####################################
# https://www.home-assistant.io/integrations/generic_thermostat/

# Газовый котел
- platform: generic_thermostat
  name: gas_boiler
  heater: switch.gas_boiler_switch_l1
  target_sensor: sensor.home_sensor_temperature
  cold_tolerance: 0.05
  hot_tolerance: 0
  precision: 0.1
  away_temp: 20

# Насос теплого пола
- platform: generic_thermostat
  name: warm_floor
  heater: switch.gas_boiler_switch_l2
  target_sensor: sensor.coolant_temperature
  ac_mode: true
  initial_hvac_mode: "cool"

# Вытяжка
- platform: generic_hygrostat
  name: kitchen
  dryer: switch.kitchen_fan_switch
  target_sensor: sensor.kitchen_sensor_humidity
  initial_hvac_mode: dry
