########################
# ВЕНТИЛЯТОРЫ НА КУХНЕ #
########################

- platform: mqtt
  name: kitchen
  availability_topic: "/zigbee-ble/bridge/state"
  command_topic: "/zigbee-ble/kitchen_fan/set/state"
  state_topic: "/zigbee-ble/kitchen_fan"
  state_value_template: "{{ value_json.state }}"
