################
# НОЧНОЙ РЕЖИМ #
################

# Автоматическое включение ночного режима
- alias: enable_night_mode
  trigger:
    - platform: time
      at: "23:00:00"
  condition:
    - condition: time
      after: "23:00:00"
      before: "07:00:00"
    - condition: state
      entity_id: alarm_control_panel.home
      state: "disarmed"
  action:
    - service: alarm_control_panel.alarm_arm_night
      data:
        entity_id: alarm_control_panel.home

# Автоматическое отключение ночного режима
- alias: disable_night_mode
  trigger:
    - platform: time
      at: "07:00:00"
  condition:
    - condition: time
      after: "07:00:00"
      before: "23:00:00"
    - condition: state
      entity_id: alarm_control_panel.home
      state: "armed_night"
  action:
    - service: alarm_control_panel.alarm_disarm
      data:
        entity_id: alarm_control_panel.home

# Действия после включения ночного режима
- alias: night_mode_enabled_actions
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home
      to: "armed_night"
  action:
    - service: script.anti_jamming_water_valve # Профилактика заклинивания водопроводного крана

# Действия после отключения ночного режима
- alias: night_mode_disabled_actions
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home
      from: "armed_night"
  action: []

################
# РЕЖИМ ОХРАНЫ #
################

# Постановка квартиры на охрану (вручную)
- alias: manual_enable_away_mode
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home
      from: "disarmed"
      to: "arming"
    - platform: state
      entity_id: switch.security_system
      from: "off"
      to: "on"
  action:
    - service: input_text.set_value # Забываем имя инициатора сработки
      data:
        entity_id: input_text.security_trigger_source
        value: ""
    - service: alarm_control_panel.alarm_arm_away # Включаем охрану
      data:
        entity_id: alarm_control_panel.home
    - service: switch.turn_on # Включаем реле охранной системы
      data:
        entity_id: switch.security_system
    - service: light.turn_off # Отключаем весь свет в квартире
      data_template: # Исключаем подсветку шлюза
        entity_id: "{% for device in states.light|rejectattr('entity_id', 'in', ['light.gateway']) %}{% if loop.first %}{% else %}, {% endif %}{{device.entity_id }}{% endfor %}"
    - service: media_player.turn_off # Отключаем телевизор в зале
      data:
        entity_id: media_player.lounge_tv
    - service: media_player.turn_off # Отключаем телевизор на кухне
      data:
        entity_id: media_player.kitchen_tv
    - service: climate.set_preset_mode # Переключаем газовое отопление на режим "away"
      data:
        entity_id: climate.gas_boiler
        preset_mode: "away"
    - service: media_player.play_media # FIXME: звуковое уведомление
      entity_id: media_player.yandex_station_4673583569717842043
      data:
        media_content_id: "Охранная сигнализация включена!"
        media_content_type: text

# Постановка квартиры на охрану (автоматически)
- alias: auto_enable_away_mode
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_occupancy
      to: "off"
      for: "24:00:00"
  condition:
    - condition: state
      entity_id: person.sergei
      state: "not_home"
    #- condition: template # Только если статус изменился не раньше, чем 12 часов назад
    #  value_template: "{{ (as_timestamp(now()) - as_timestamp(states.person.sergei.last_changed)) > 43200 }}"
  action:
    - service: alarm_control_panel.alarm_arm_away
      data:
        entity_id: alarm_control_panel.home

# Снятие квартиры с охраны (вручную)
- alias: manual_disable_away_mode
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home
      to: "disarmed"
    - platform: state
      entity_id: switch.security_system
      from: "on"
      to: "off"
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: switch.security_system
        state: "on"
      - condition: state
        entity_id: alarm_control_panel.home
        state:
          - armed_away
          - arming
          - pending
          - triggered
  action:
    - service: input_text.set_value # Забываем имя инициатора сработки
      data:
        entity_id: input_text.security_trigger_source
        value: ""
    - service: alarm_control_panel.alarm_disarm # Отключаем охрану
      data:
        entity_id: alarm_control_panel.home
    - service: switch.turn_off # Отключаем реле охранной системы
      data:
        entity_id: switch.security_system
    - service: media_player.play_media # FIXME: звуковое уведомление
      entity_id: media_player.yandex_station_4673583569717842043
      data:
        media_content_id: "Охранная сигнализация отключена!"
        media_content_type: text
    - service: automation.trigger # Включаем ночной режим, если это необходимо
      data:
        entity_id: automation.enable_night_mode
        skip_condition: false
    - service: climate.set_preset_mode # Переключаем газовое отопление на обычный режим
      data:
        entity_id: climate.gas_boiler
        preset_mode: "none"

# Снятие квартиры с охраны (автоматически)
- alias: auto_disable_away_mode
  trigger:
    - platform: state # Открыта входная дверь
      entity_id: binary_sensor.hallway_door_contact
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home
      state:
        - armed_away
        #- pending
    - condition: state
      entity_id: person.sergei
      state: "home"
    #- condition: template # Только если статус "home" для "person.sergei" установлен в течении последних 5 минут
    #  value_template: "{{ (as_timestamp(now()) - as_timestamp(states.person.sergei.last_changed)) < 300 }}"
  action:
    - service: alarm_control_panel.alarm_disarm # Снимаем с охраны
      data:
        entity_id: alarm_control_panel.home
    - condition: state # Если свет в коридоре отключен
      entity_id: light.hallway
      state: "off"
    - condition: numeric_state # И там темно
      entity_id: sensor.hallway_motion_illuminance
      below: 5
    - service: light.turn_on # Включаем свет
      entity_id: light.hallway

# Действия во время arming/pending-ожидания
- alias: enable_arming_pending_away_mode
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home
      to: "arming"
    - platform: state
      entity_id: alarm_control_panel.home
      to: "pending"
  action:
    - service: light.turn_on
      data:
        entity_id: light.gateway
        rgb_color: [255, 63, 0]

# Действия после arming/pending-ожидания
- alias: disable_arming_pending_away_mode
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home
      from: "arming"
    - platform: state
      entity_id: alarm_control_panel.home
      from: "pending"
  action:
    - service: light.turn_off
      entity_id: light.gateway

# Срабатывание охранной сигнализации (условия)
- alias: conditions_triggered_away_mode
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.hallway_door_contact # Открыта входная дверь
        - binary_sensor.hallway_motion_occupancy # Обнаружено движение в коридоре
        - binary_sensor.bathroom_motion_occupancy # Обнаружено движение в ванной
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home
      state: "armed_away"
  action:
    - service: input_text.set_value # Запоминаем имя инициатора сработки
      data_template:
        entity_id: input_text.security_trigger_source
        value: "{{ trigger.from_state.attributes.friendly_name }}"
    - service: alarm_control_panel.alarm_trigger # Инициируем срабатывание
      data:
        entity_id: alarm_control_panel.home

# Срабатывание охранной сигнализации (действия)
- alias: enable_triggered_away_mode
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home
      to: "triggered"
  action:
    - service: notify.notify # Оповещаем пользователя
      data_template:
        title: "Внимание!"
        message: "{{ states('input_text.security_trigger_source') }} вызвал срабатывание охранной сигнализации!"
    - service: light.turn_on # Включаем подсветку шлюза
      data:
        entity_id: light.gateway
        rgb_color: [255, 0, 0]
    - service: media_player.play_media # FIXME: включаем звуковую сирену
      entity_id: media_player.yandex_station_4673583569717842043
      data:
        media_content_id: '<speaker audio="alice-sounds-things-siren-2.opus">'
        media_content_type: text

# Окончание срабатывания охранной сигнализации (действия)
- alias: disable_triggered_away_mode
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home
      from: "triggered"
  action:
    - service: yandex_station.send_command # FIXME: отключаем звуковую сирену
      entity_id: media_player.yandex_station_4673583569717842043
      data:
        command: sendText
        text: "Стоп"
    - service: light.turn_off # Отключаем подсветку шлюза
      data:
        entity_id: light.gateway
    - service: input_text.set_value # Забываем имя инициатора сработки
      data:
        entity_id: input_text.security_trigger_source
        value: ""
