##################
# ВАННАЯ КОМНАТА #
##################

# Автоматическое включение света в ванной
- alias: turnon_bathroom_light_when_bathroom_motion_detected
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_motion_occupancy
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home
      state:
        - disarmed
        - armed_night
  action:
    - service: light.turn_on
      data:
        entity_id: light.bathroom

# Автоматическое отключение света в ванной
- alias: turnoff_bathroom_light_when_bathroom_motion_lost
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_motion_occupancy
      to: "off"
      for: "00:10:00"
  condition:
    - condition: state
      entity_id: light.bathroom
      state: "on"
  action:
    - service: light.turn_off
      data:
        entity_id: light.bathroom

# Оповещение о срабатывании датчика протечки
- alias: leak_sensor_triggering
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.bathroom_leak_1_water_leak
        - binary_sensor.bathroom_leak_2_water_leak
        - binary_sensor.kitchen_leak_water_leak
      to: "on"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.water_valve_switch
    - service: notify.notify
      data_template:
        title: "Внимание!"
        message: "Сработал {{ trigger.from_state.attributes.friendly_name | lower }}! Водоснабжение квартиры было отключено."

# Управление гигростатом в зависимости от состояния освещения и ночного режима
- alias: control_bathroom_climate_when_light_or_night_changed
  trigger:
    - platform: state
      entity_id: light.bathroom
    - platform: state
      entity_id: alarm_control_panel.home
  action:
    - service: switch.turn_off
      entity_id: switch.bathroom_fan_hygrostat

# Включение/отключение вентиляции по нажатии на кнопку
- alias: toggle_bathroom_fan_when_button_pushed
  trigger:
    - platform: state
      entity_id: sensor.bathroom_button_click
      to: "single"
  action: # Переключаем гигростат
    - service: switch.toggle
      entity_id: switch.bathroom_fan_hygrostat

# Автоматическое изменение предельного уровня влажности
- alias: autoset_bathroom_climate_max_humidity_level
  trigger:
    - platform: state
      entity_id: sensor.home_sensor_humidity
  action:
    - service: climate.set_humidity
      data_template:
        entity_id: climate.bathroom
        humidity: "{{ (states('sensor.home_sensor_humidity') | round) + 10 | int }}"
