##################
# ВАННАЯ КОМНАТА #
##################


# Оповещение о срабатывании датчика протечки
- alias: leak_sensor_triggering
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.bathroom_leak_1
        - binary_sensor.bathroom_leak_2
        - binary_sensor.kitchen_leak
      to: "on"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.water_valve
    - service: notify.notify
      data_template:
        title: "Внимание!"
        message: "Сработал {{ trigger.from_state.attributes.friendly_name | lower }}! Водоснабжение квартиры было отключено."


# Управление гиростатом в зависимости от состояния освещения и ночного режима
- alias: control_bathroom_climate_when_light_changed # Включили свет
  trigger:
    - platform: state
      entity_id: light.bathroom
    - platform: state
      entity_id: alarm_control_panel.home
  action:
    - service: switch.turn_off
      entity_id: switch.bathroom_fan


# Включение/отключение вентиляции по нажатии на кнопку
- alias: toggle_bathroom_fan_when_button_pushed
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_button_single
      to: "on"
  action: # Переключаем гиростат
    - service: switch.toggle
      entity_id: switch.bathroom_fan
