# Управление подсветкой шлюза в ночном режиме
- alias: turnon_gateway_light_when_hallway_motion_detected # Обнаружено движение в комнате
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_occupancy
      to: "on"
  condition:
    - condition: state # Ночной режим включен
      entity_id: alarm_control_panel.home
      state: "armed_night"
    - condition: numeric_state # И в комнате темно
      entity_id: sensor.hallway_motion_illuminance
      below: 5
  action: # Включаем подсветку
    - service: light.turn_on
      data:
        entity_id: light.gateway
        rgb_color: [255, 127, 0]
        brightness: 127
- alias: turnoff_gateway_light_when_hallway_motion_lost # Движение закончено или включили свет
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_occupancy
      to: "off"
    - platform: state
      entity_id: light.hallway
      to: "on"
  condition:
    - condition: state # Ночной режим включен
      entity_id: alarm_control_panel.home
      state: "armed_night"
  action: # Выключаем подсветку
    - service: light.turn_off
      data:
        entity_id: light.gateway

# Автоматическое отключение света в коридоре
- alias: turnoff_hallway_light_when_hallway_motion_lost
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_occupancy
      to: "off"
      for: "00:10:00"
  condition:
    - condition: state
      entity_id: light.hallway
      state: "on"
  action:
    - service: light.turn_off
      data:
        entity_id: light.hallway

# Таймаут для датчика движения в коридоре
- alias: hallway_motion_off_delay
  mode: restart
  trigger:
    - platform: mqtt
      topic: "/zigbee/hallway_motion"
  condition:
    condition: template
    value_template: '{{ trigger.payload_json.occupancy == true }}'
  action:
    - delay:
        seconds: >
          {{ (state_attr('binary_sensor.hallway_motion_occupancy', 'occupancy_timeout') | int) }}
    - service: mqtt.publish
      data:
        topic: "/zigbee/hallway_motion"
        payload_template: >
          {
            "battery": {{ (state_attr('binary_sensor.hallway_motion_occupancy', 'battery') | int) }},
            "illuminance": {{ (state_attr('binary_sensor.hallway_motion_occupancy', 'illuminance') | int) }},
            "linkquality": {{ (state_attr('binary_sensor.hallway_motion_occupancy', 'linkquality') | int) }},
            "occupancy": false,
            "occupancy_timeout": {{ (state_attr('binary_sensor.hallway_motion_occupancy', 'occupancy_timeout') | int) }},
            "voltage": {{ (state_attr('binary_sensor.hallway_motion_occupancy', 'voltage') | float) }}
          }
        retain: true

# Кнопка дверного звонка (тестирование)
- alias: hallway_doorbell_button_pushed
  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_button_binary_input_1
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.home
      state: "disarmed"
  action:
    - service: media_player.play_media
      entity_id: media_player.yandex_station_ff98f02956241bb6fce15af6
      data:
        media_content_id: '<speaker audio="alice-sounds-game-8-bit-phone-1.opus">'
        media_content_type: text
