# Управление подсветкой шлюза в ночном режиме
- alias: turnon_gateway_light_when_hallway_motion_detected # Обнаружено движение в комнате
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_occupancy
      to: "on"
  condition:
    - condition: state # Ночной режим включен
      entity_id: alarm_control_panel.home
      state: "armed_night"
    - condition: numeric_state # И в комнате темно
      entity_id: sensor.hallway_motion_illuminance
      below: 5
  action: # Включаем подсветку
    - service: light.turn_on
      data:
        entity_id: light.gateway
        rgb_color: [255, 127, 0]
        brightness: 127
- alias: turnoff_gateway_light_when_hallway_motion_lost # Движение закончено или включили свет
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_occupancy
      to: "off"
    - platform: state
      entity_id: light.hallway
      to: "on"
  condition:
    - condition: state # Ночной режим включен
      entity_id: alarm_control_panel.home
      state: "armed_night"
  action: # Выключаем подсветку
    - service: light.turn_off
      data:
        entity_id: light.gateway

# Автоматическое отключение света в коридоре
- alias: turnoff_hallway_light_when_hallway_motion_lost
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_motion_occupancy
      to: "off"
      for: "00:05:00"
  condition:
    - condition: state
      entity_id: light.hallway
      state: "on"
  action:
    - service: light.turn_off
      data:
        entity_id: light.hallway

# Таймаут для датчика движения в коридоре
- alias: hallway_motion_off_delay
  mode: restart
  trigger:
    - platform: mqtt
      topic: "/zigbee/hallway_motion"
  condition:
    condition: template
    value_template: '{{ trigger.payload_json.occupancy == true }}'
  action:
    - delay: 00:00:07
    - service: mqtt.publish
      data:
        topic: "/zigbee/hallway_motion"
        payload: '{"occupancy": false}'
        retain: true
