#########
# КУХНЯ #
#########

# Управление гигростатом в зависимости от ночного режима
- alias: control_kitchen_climate_when_night_changed
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home
  action:
    - service: switch.turn_off
      entity_id: switch.kitchen_fan_hygrostat

# Автоматическое изменение предельного уровня влажности
- alias: autoset_kitchen_climate_max_humidity_level
  trigger:
    - platform: state
      entity_id: sensor.home_sensor_humidity
  action:
    - service: climate.set_humidity
      data_template:
        entity_id: climate.kitchen
        humidity: "{{ (states('sensor.home_sensor_humidity') | round) + 5 | int }}"
