# Управление гиростатом в зависимости от ночного режима
- alias: control_kitchen_climate_when_night_changed
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home
  action:
    - service: switch.turn_off
      entity_id: switch.kitchen_fan
