# Повышенный уровень радиации
- alias: high_radiation_notify
  trigger:
    - platform: numeric_state
      entity_id: sensor.radiation_level
      above: 30
  action:
    - service: notify.notify
      data_template:
        title: "Внимание!"
        message: "Радиационный фон превысил норму и составляет {{ trigger.to_state.state | int }} микрорентген в час!"
