# Настольный компьютер
# https://www.home-assistant.io/integrations/universal/
- platform: universal
  name: desktop_pc
  children: []
  commands:
    turn_on:
      service: switch.turn_on
      data:
        entity_id: switch.desktop_pc
    turn_off:
      service: switch.turn_off
      data:
        entity_id: switch.desktop_pc
  attributes:
    state: switch.desktop_pc
